### ISSUE TITLE
Investigate why there is a certain gap between contact ids on postgres

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific#881]

**Comment by pankaj-ag** [comment]
Remove the upsert from this function
defp do_contact_opted_in(phone, organization_id, utc_time) do
that might be causing the jump in contact ids

**Comment by dlobo** [comment]
We should track this on prodution next week. the fix has been merged into master

**Comment by pankaj-ag** [comment]
We will track it on production for a few days and then close the issue.

**Comment by pankaj-ag** [comment]
This error is still persists. We need to dig deeper. 
![image](https://user-images.githubusercontent.com/10670690/104327617-fdc02d80-5510-11eb-84ca-f2c7ae05625d.png)

**Comment by pankaj-ag** [comment]
@AkhileshNegi can you make the required changes for the optout contact as well. I think it will fix this issue completely.

**Comment by pankaj-ag** [comment]
It looks good now. Closing this one.
